### ISSUE TITLE
Output request/response headers to stderr

### ISSUE THREAD

**Issue by dylanowen** [bayne/dot-http#41]
I've been using dot-http for some scripting tasks, it'd be nice to have the response body be the only thing output over stdout, much like curl.

https://github.com/bayne/dot-http/compare/master...dylanowen:stderr?expand=1

**Comment by bayne** [comment]
I wanted to reserve stderr for other purposes (eventually wanting to print out metrics such as request time etc)

My end-goal was to have a `--response-output-format="FORMAT_STRING_HERE"` where the format string could be constructed to suppress the headers. As a convenience, I'm imagining creating flags that are synonymous to an expanded form of `--response-output-format="FORMAT_STRING_HERE"`

For example, if we had a response like
```
POST http://httpbin.org/post

HTTP/1.1 200 OK
date: Sat, 15 Feb 2020 19:29:22 GMT

{
  "origin": "127.0.0.1",
  "url": "http://httpbin.org/post"
}
```

The response format string would be `%R\n%S\n%H\n%B` where
- `%R` is `POST http://httpbin.org/post`
- `%S` is  `HTTP/1.1 200 OK`
- `%H` are the headers
- `%B` is the body

So to solve your problem, I would want the solution to be:
```
--only-output-body
``` 
which is synonymous with
```
--response-output-format="%B"
```

For the time being (since none of the response format exists yet), a mergeable change would be to:

1. Create a new flag `--only-output-body`
2. Update the response handler to prevent printing other parts of the response when that flag is set

**Comment by tglman** [comment]
Hi, 
I was also experimenting a bit with outputs and i did my own way to print out things that actually introduced 3 levels, quite(print nothing), normal(current printing) and verbose(print full request and response), anyway i would not mind to re-implement it to follow this approach that is actually more detailed and flexible.

I do have though one missing specification from this issue is how to set the printing of the request shall we define another `--request-output-format="..."` with the same options? 
as well i see useful a set of shortcuts like "--quite" to shut all the printing, what would be for you any other possible shortcut ?

Regards

**Comment by tglman** [comment]
Hi, 
A while ago I wrote a PR that implement the "output format" here it is: https://github.com/bayne/dot-http/pull/53 could you let me know if this is the solution you expect or prefer a different approach?

Regards
